#ifndef PARAMS_H
#define PARAMS_H

#define PARAM_NAME "Viper-128"

#define MLWQ_N 256
#define MLWQ_Q 3329

#define SEEDBYTES 32
#define HASHBYTES 32

#define MLWQ_K 2

#define MLWQ_ETA_S 2
#define MLWQ_ETA_R 2
#define MLWQ_ETA1 MLWQ_ETA_S

#define BIT_PK 10
#define BIT_U  9
#define BIT_V  5

#define P_PK (1 << BIT_PK)
#define P_U  (1 << BIT_U)
#define P_V  (1 << BIT_V)

#define MSG_BITS 1
#define MU_BYTES 32
#define MU_BITS  (MU_BYTES * 8)

#define MLWQ_SSBYTES 32

#define MLWQ_POLYBYTES ((MLWQ_N * BIT_PK) / 8)
#define MLWQ_POLYVECBYTES (MLWQ_K * MLWQ_POLYBYTES)

#define MLWQ_POLY_U_BYTES ((MLWQ_N * BIT_U) / 8)
#define MLWQ_POLYVECCOMPRESSEDBYTES (MLWQ_K * MLWQ_POLY_U_BYTES)

#define MLWQ_POLYCOMPRESSEDBYTES ((MLWQ_N * BIT_V) / 8)

#define MLWQ_CIPHERTEXTBYTES \
    (MLWQ_POLYVECCOMPRESSEDBYTES + MLWQ_POLYCOMPRESSEDBYTES + SEEDBYTES)
#define MLWQ_PUBLICKEYBYTES (MLWQ_POLYVECBYTES + SEEDBYTES)
#define MLWQ_SECRETKEYBYTES MLWQ_POLYVECBYTES
#define MLWQ_KEM_SECRETKEYBYTES \
    (MLWQ_POLYVECBYTES + MLWQ_PUBLICKEYBYTES + HASHBYTES + SEEDBYTES)

/*
 * Compatibility aliases for the Kyber-derived m4speed code. Keep these as
 * aliases, not independent parameters, so the C glue migrates toward MLWQ
 * names while the assembly-facing code can still compile during the port.
 */
#define KYBER_K MLWQ_K
#define KYBER_N MLWQ_N
#define KYBER_Q MLWQ_Q

#define KYBER_ETA1 MLWQ_ETA_S
#define KYBER_ETA2 MLWQ_ETA_R

#define KYBER_SYMBYTES SEEDBYTES
#define KYBER_SSBYTES  MLWQ_SSBYTES

#define KYBER_POLYBYTES              MLWQ_POLYBYTES
#define KYBER_POLYVECBYTES           MLWQ_POLYVECBYTES

#define KYBER_POLYCOMPRESSEDBYTES    MLWQ_POLYCOMPRESSEDBYTES
#define KYBER_POLYVECCOMPRESSEDBYTES MLWQ_POLYVECCOMPRESSEDBYTES

#define KYBER_INDCPA_MSGBYTES       MU_BYTES
#define KYBER_INDCPA_PUBLICKEYBYTES MLWQ_PUBLICKEYBYTES
#define KYBER_INDCPA_SECRETKEYBYTES MLWQ_SECRETKEYBYTES
#define KYBER_INDCPA_BYTES          MLWQ_CIPHERTEXTBYTES

#define KYBER_PUBLICKEYBYTES  MLWQ_PUBLICKEYBYTES
#define KYBER_SECRETKEYBYTES  MLWQ_KEM_SECRETKEYBYTES
#define KYBER_CIPHERTEXTBYTES MLWQ_CIPHERTEXTBYTES

#endif
