#ifndef VIPER_PARAMS_H
#define VIPER_PARAMS_H

#define VIPER_LEVEL 256

/* MAMBA-Viper implementation and implementation support layer where applicable. */

#include <stddef.h>
#include <stdint.h>

#ifndef VIPER_LEVEL
#define VIPER_LEVEL 128
#endif

#define VIPER_N 256
#define VIPER_Q 4096
#define VIPER_Q_MASK 4095
#define VIPER_SEEDBYTES 32
#define VIPER_MU_BYTES 32
#define VIPER_SHARED_SECRET_BYTES 32
#if VIPER_LEVEL == 128
#define VIPER_K 2
#define VIPER_ETA_S 1
#define VIPER_ETA_R 1
#define VIPER_T_PK 9
#define VIPER_T_U 9
#define VIPER_T_V 3
#define VIPER_PUBLICKEYBYTES 608
#define VIPER_CIPHERTEXTBYTES 704
#define VIPER_SECRETKEYBYTES 1440
#define VIPER_ALGNAME "MAMBA-Viper-128"
#elif VIPER_LEVEL == 192
#define VIPER_K 3
#define VIPER_ETA_S 2
#define VIPER_ETA_R 2
#define VIPER_T_PK 10
#define VIPER_T_U 10
#define VIPER_T_V 3
#define VIPER_PUBLICKEYBYTES 992
#define VIPER_CIPHERTEXTBYTES 1088
#define VIPER_SECRETKEYBYTES 2208
#define VIPER_ALGNAME "MAMBA-Viper-192"
#elif VIPER_LEVEL == 256
#define VIPER_K 4
#define VIPER_ETA_S 2
#define VIPER_ETA_R 2
#define VIPER_T_PK 10
#define VIPER_T_U 10
#define VIPER_T_V 5
#define VIPER_PUBLICKEYBYTES 1312
#define VIPER_CIPHERTEXTBYTES 1472
#define VIPER_SECRETKEYBYTES 2912
#define VIPER_ALGNAME "MAMBA-Viper-256"
#else
#error "Unsupported VIPER_LEVEL; use 128, 192, or 256"
#endif

#define VIPER_POLYBYTES_12 (VIPER_N * 12 / 8)
#define VIPER_SECRETKEY_PKE_BYTES (VIPER_K * VIPER_POLYBYTES_12)
#define VIPER_PACKED_PK_POLYBYTES (VIPER_N * VIPER_T_PK / 8)
#define VIPER_PACKED_U_POLYBYTES (VIPER_N * VIPER_T_U / 8)
#define VIPER_PACKED_V_BYTES (VIPER_N * VIPER_T_V / 8)
#define VIPER_PACKED_B_BYTES (VIPER_K * VIPER_PACKED_PK_POLYBYTES)
#define VIPER_PACKED_U_BYTES (VIPER_K * VIPER_PACKED_U_POLYBYTES)

#define VIPER_DERIVED_PUBLICKEYBYTES (VIPER_SEEDBYTES + VIPER_PACKED_B_BYTES)
#define VIPER_DERIVED_CIPHERTEXTBYTES (VIPER_MU_BYTES + VIPER_PACKED_U_BYTES + VIPER_PACKED_V_BYTES)
#define VIPER_DERIVED_SECRETKEYBYTES (VIPER_SECRETKEY_PKE_BYTES + VIPER_PUBLICKEYBYTES + 32 + 32)

enum {
  VIPER_PUBLICKEY_SIZE_CHECK = 1 / (int)(VIPER_PUBLICKEYBYTES == VIPER_DERIVED_PUBLICKEYBYTES),
  VIPER_CIPHERTEXT_SIZE_CHECK = 1 / (int)(VIPER_CIPHERTEXTBYTES == VIPER_DERIVED_CIPHERTEXTBYTES),
  VIPER_SECRETKEY_SIZE_CHECK = 1 / (int)(VIPER_SECRETKEYBYTES == VIPER_DERIVED_SECRETKEYBYTES),
  VIPER_SHARED_SECRET_SIZE_CHECK = 1 / (int)(VIPER_SHARED_SECRET_BYTES == 32)
};

#endif
