#ifndef PARAMS_H
#define PARAMS_H

#define PARAM_NAME "Viper-192"

#define MLWQ_N 256
#define MLWQ_Q 3329

#define SEEDBYTES 32
#define HASHBYTES 32

#define MLWQ_K 3

#define MLWQ_ETA_S 3
#define MLWQ_ETA_R 2
#define MLWQ_ETA1 MLWQ_ETA_S

#define BIT_PK 10
#define BIT_U  10
#define BIT_V  5

#define P_PK (1 << BIT_PK)
#define P_U  (1 << BIT_U)
#define P_V  (1 << BIT_V)

#define MSG_BITS 1
#define MU_BYTES 32
#define MU_BITS  (MU_BYTES * 8)

#define MLWQ_SSBYTES 32

#define MLWQ_POLYBYTES ((MLWQ_N * BIT_PK) / 8)
#define MLWQ_POLYVECBYTES (MLWQ_K * MLWQ_POLYBYTES)

#define MLWQ_POLY_U_BYTES ((MLWQ_N * BIT_U) / 8)
#define MLWQ_POLYVECCOMPRESSEDBYTES (MLWQ_K * MLWQ_POLY_U_BYTES)

#define MLWQ_POLYCOMPRESSEDBYTES ((MLWQ_N * BIT_V) / 8)

#define MLWQ_CIPHERTEXTBYTES \
    (MLWQ_POLYVECCOMPRESSEDBYTES + MLWQ_POLYCOMPRESSEDBYTES + SEEDBYTES)
#define MLWQ_PUBLICKEYBYTES (MLWQ_POLYVECBYTES + SEEDBYTES)
#define MLWQ_SECRETKEYBYTES MLWQ_POLYVECBYTES
#define MLWQ_KEM_SECRETKEYBYTES \
    (MLWQ_POLYVECBYTES + MLWQ_PUBLICKEYBYTES + HASHBYTES + SEEDBYTES)

#endif
