SOURCES = kem.c nike_m4.c poly_m4.c toom_m4.c error_correction_m4.c \
          crypto_stream_chacha20.c ../../../common/randombytes.c
HEADERS = api.h params.h nike.h poly.h toom.h error_correction.h \
          reduce.h crypto_stream_chacha20.h

INCPATH ?= ../../../common
CFLAGS += -I$(INCPATH)
